### ISSUE TITLE
Create Posts DB schema and API endpoint

### ISSUE THREAD

**Issue by pacbac** [CS130-W20/team-B6#25]
## User Story
As a user, I would like to fetch posts data on the app so that I can see what the news details are.

## Posts Schema
Posts:
- id
- News article link
- Author user id
- Opinion description
- Timestamp of creation

**Comment by rishabhjain1198** [comment]
Let's say the frontend can retrieve aforementioned data for a specific post with post ID `xyz` using a GET on:
`/posts/xyz`
