### ISSUE TITLE
Create POST endpoint to change name, email, user description, profile picture.

### ISSUE THREAD

**Issue by pacbac** [CS130-W20/team-B6#39]
## User Story
As a user, I would like to change my info when desired so that it more accurately reflects me.

## Detailed Description
Should update the corresponding user entry in the DB. Will be used in the edit profile page.

## Acceptance Criteria
- [x] Endpoint created to edit user info (request sent as JSON)
- [x] Function corresponding to the endpoint will write to the database to update the user entry

**Comment by rishabhjain1198** [comment]
Decided to make it a PUT endpoint since it should ideally be idempotent. Haven't implemented the upload API yet for the profile picture (thinking of just using the Imgur API).

**Comment by pacbac** [comment]
Right now I'm using firebase purely just for cloud storage, storing profile pics, which actually works very well. In the code, it will know exactly how to request from firebase directly for the profile pic URL, so actually that column in the DB table is no longer needed. ~~They can just upload their profile pic after they sign up, which will return back a static img URL that can then be sent to the DB.~~ I've already set it in the frontend that if the user doesn't have a profile pic URL in the database, it will just automatically load the default profile picture.
